version: "3"

services:

  db-broker:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker

  broker:
    image: silintl/idp-id-broker:develop-4.0
    ports:
      - "10000:80"
    depends_on:
      - db-broker
    environment:
      API_ACCESS_KEYS: abc123abc123
      APP_ENV: test
      IDP_NAME: development
      LDAP_ADMIN_PASSWORD: admin
      LDAP_ADMIN_USERNAME: cn=Manager,dc=acme,dc=org
      LDAP_BASE_DN: dc=acme,dc=org
      LDAP_DOMAIN_CONTROLLERS: ldap
      LDAP_USE_SSL: "false"
      LDAP_USE_TLS: "false"
      LOGENTRIES_KEY:
      EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      EMAIL_SERVICE_accessToken: fake
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: fake
      MIGRATE_PW_FROM_LDAP: "false"
      MYSQL_DATABASE: broker
      MYSQL_HOST: db-broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: broker
      NOTIFICATION_EMAIL: "dummy@example.com"
    command: whenavail db-broker 3306 100 /data/run.sh

  phpmyadmin-broker:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    depends_on:
      - db-broker
    environment:
      PMA_HOST: db-broker
      PMA_USER: broker
      PMA_PASSWORD: broker

  db-ssp:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: ssp
      MYSQL_USER: ssp
      MYSQL_PASSWORD: ssp

  ssp:
    image: silintl/ssp-base:4.3.0
    ports:
      - "80:80"
    depends_on:
      - broker
      - db-ssp
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "sortalongrandomstring"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_COLOR_SCHEME: "orange-light_blue"
      THEME_USE: material:material
      BASE_URL_PATH: http://ssp.local/
      ID_BROKER_ACCESS_TOKEN: abc123abc123
      ID_BROKER_BASE_URI: http://broker
      ID_BROKER_ASSERT_VALID_IP: "false"
      IDP_DOMAIN_NAME: ssp.local
      IDP_NAME: development
      LOGENTRIES_KEY:
      MYSQL_HOST: db-ssp
      MYSQL_DATABASE: ssp
      MYSQL_USER: ssp
      MYSQL_PASSWORD: ssp
      RECAPTCHA_SITE_KEY: asdf
      RECAPTCHA_SECRET: adff
      PASSWORD_CHANGE_URL: http://pw-ui.local:9000/#/change
      PASSWORD_FORGOT_URL: http://pw-ui.local:9000/#/forgot
    volumes:
      - ./ssp/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./ssp/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./ssp/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./ssp/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    command: whenavail db-ssp 3306 100 /data/run-idp.sh

  phpmyadmin-ssp:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8002:80"
    depends_on:
      - db-ssp
    environment:
      PMA_HOST: db-ssp
      PMA_USER: ssp
      PMA_PASSWORD: ssp

  db-pw:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tP@ss!
      MYSQL_DATABASE: pw-api
      MYSQL_USER: pw-api
      MYSQL_PASSWORD: pw-api

  pw-api:
    image: silintl/idp-pw-api:develop-3.0
    ports:
      - "8080:80"
    depends_on:
      - db-pw
    volumes:
      - ./pw-api/config.php:/data/common/config/local.php
    environment:
      MYSQL_HOST: db-pw
      MYSQL_DATABASE: pw-api
      MYSQL_USER: pw-api
      MYSQL_PASSWORD: pw-api
      IDP_NAME: development
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_CACHE_DIR: /composer
      ALERTS_EMAIL_ENABLED: "false"
      LOGO_URL: http://pw-ui.local:9000/#/welcome
      EMAILER_CLASS: \tests\mock\emailer\FakeEmailer
      EMAIL_SERVICE_baseUrl: http://email
      EMAIL_SERVICE_accessToken: abc123
      EMAIL_SERVICE_assertValidIp: "false"
      ADMIN_EMAIL: admin@domain.com
      FROM_EMAIL: admin@domain.com
      FROM_NAME: Your friendly Help Desk team
      FRONT_COOKIE_SECURE: "false"
      RECAPTCHA_REQUIRED: "false"
      RECAPTCHA_SITE_KEY:
      RECAPTCHA_SECRET_KEY:
      UI_URL: http://pw-ui.local:9000/#
      UI_CORS_ORIGIN: http://pw-ui.local:9000
      HELP_CENTER_URL: https://google.com/
      LOGENTRIES_KEY:
      SUPPORT_PHONE:
      SUPPORT_EMAIL:
      SUPPORT_URL:
      SUPPORT_FEEDBACK:
      ZXCVBN_API_BASEURL: http://zxcvbn:3000
      ACCESS_TOKEN_HASH_KEY: nice long random string here
      ALERTS_EMAIL: admin@domain.com
      AUTH_SAML_signRequest: "false"
      AUTH_SAML_checkResponseSigning: "false"
      AUTH_SAML_requireEncryptedAssertion: "false"
      AUTH_SAML_idpCertificate: MIIDzzCCAregAwIBAgIJAPlZYTAQSIbHMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOQzEPMA0GA1UEBwwGV2F4aGF3MQwwCgYDVQQKDANTSUwxDTALBgNVBAsMBEdUSVMxDjAMBgNVBAMMBVN0ZXZlMSQwIgYJKoZIhvcNAQkBFhVzdGV2ZV9iYWd3ZWxsQHNpbC5vcmcwHhcNMTYxMDE3MTIzMTQ1WhcNMjYxMDE3MTIzMTQ1WjB+MQswCQYDVQQGEwJVUzELMAkGA1UECAwCTkMxDzANBgNVBAcMBldheGhhdzEMMAoGA1UECgwDU0lMMQ0wCwYDVQQLDARHVElTMQ4wDAYDVQQDDAVTdGV2ZTEkMCIGCSqGSIb3DQEJARYVc3RldmVfYmFnd2VsbEBzaWwub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArssOaeKbdOQFpN6bBolwSJ/6QFBXA73Sotg60anx9v6aYdUTmi+b7SVtvOmHDgsD5X8pN/6Z11QCZfTYg2nW3ZevGZsj8W/R6C8lRLHzWUr7e7DXKfj8GKZptHlUs68kn0ndNVt9r/+irJe9KBdZ+4kAihykomNdeZg06bvkklxVcvpkOfLTQzEqJAmISPPIeOXes6hXORdqLuRNTuIKarcZ9rstLnpgAs2TE4XDOrSuUg3XFnM05eDpFQpUb0RXWcD16mLCPWw+CPrGoCfoftD5ZGfll+W2wZ7d0kQ4TbCpNyxQH35q65RPVyVNPgSNSsFFkmdcqP9DsFqjJ8YC6wIDAQABo1AwTjAdBgNVHQ4EFgQUD6oyJKOPPhvLQpDCC3027QcuQwUwHwYDVR0jBBgwFoAUD6oyJKOPPhvLQpDCC3027QcuQwUwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAA6tCLHJQGfXGdFerQ3J0wUu8YDSLb0WJqPtGdIuyeiywR5ooJf8G/jjYMPgZArepLQSSi6t8/cjEdkYWejGnjMG323drQ9M1sKMUhOJF4po9R3t7IyvGAL3fSqjXA8JXH5MuGuGtChWxaqhduA0dBJhFAtAXQ61IuIQF7vSFxhTwCvJnaWdWD49sG5OqjCfgIQdY/mw70e45rLnR/bpfoigL67sTJxy+Kx2ogbvMR6lITByOEQFMt7BYpMtXrwvKUM7k9NOo1jREmJacC8PTx//jRhCWwzUj1RsfIri24BuITrawwqMsYl8DZiiwMpjUf9m4NPaf4E7+QRpzo+MCcg==
      AUTH_SAML_spCertificate: MIIDtTCCAp2gAwIBAgIJAK2cyEwuxdADMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMTcwNDI4MTMyNjA2WhcNMjcwNDI4MTMyNjA2WjBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtVzLISMbdMHa7yPQgcdmH5khNTGv9zchvL15dEmsAgFIHZQULm72lclpsThdpb95r6lbnEqfhidTVnqpFQv755gzxn4r+ScFCTMPdsdK+Flh5Ej10VOYfBepBhrhU7mZhF4UFFHvx4karENyCQeEjw2JCNmDO/hDX5vluYip09TfEQSbCO6zYoEx6Z+PoDauYBYhQka3H8DDhSg/vjTuHoos4bkW/gRbgVAAOGgtx6gp4djb4WlldMKEjXcKihLGQXYPw5Ur2dHLOxuSAkxSnFrx+Eb/26/dU0RZC/a2ipujCQhjT9uiw1x7orSjDK1SFHq9Xlie0e0W8sVrgZtwYQIDAQABo4GnMIGkMB0GA1UdDgQWBBRxdpPqYNHv58zusXJyeb9L1Iv3pjB1BgNVHSMEbjBsgBRxdpPqYNHv58zusXJyeb9L1Iv3pqFJpEcwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZIIJAK2cyEwuxdADMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEUr+4aDqozvb3P+53vjYR1OIyJdE4EhZjLpT2xwIqhQVaED7nfxaY0E3znE53YoNUlDz8/+3zwU6aQxeZtD84Tbunv9X8hWgt9k97ib04pmHZe9Cp0B61Yv0aUmKGlFEPEzG84jfjnILhS0fxePIjKpot6bt3EJ1XnfLvrNGBeWgQao3qGaXVwK/9gJOFUGLRG2X34AI2nTNAbr2Sexvn8yVarY41VC08nGoqrFnoKf3zi1GH6Pp8XSVCt4bU7u/I9XBsUpagVFxkw2wJZW9kBkfQLqtOwgRv2n4F4Ftxo9wLZJ5bPMcJf+R6PsJJQRslsW7NSFjoXIPnVXEF6nxQk=
      AUTH_SAML_spPrivateKey: MIIEpQIBAAKCAQEAtVzLISMbdMHa7yPQgcdmH5khNTGv9zchvL15dEmsAgFIHZQULm72lclpsThdpb95r6lbnEqfhidTVnqpFQv755gzxn4r+ScFCTMPdsdK+Flh5Ej10VOYfBepBhrhU7mZhF4UFFHvx4karENyCQeEjw2JCNmDO/hDX5vluYip09TfEQSbCO6zYoEx6Z+PoDauYBYhQka3H8DDhSg/vjTuHoos4bkW/gRbgVAAOGgtx6gp4djb4WlldMKEjXcKihLGQXYPw5Ur2dHLOxuSAkxSnFrx+Eb/26/dU0RZC/a2ipujCQhjT9uiw1x7orSjDK1SFHq9Xlie0e0W8sVrgZtwYQIDAQABAoIBAEaRIIh4PIqlkyZRbSPSDi5lSsKD3s/2J65kmwlgUQlGrmSz5VZb3p5RjEpkgCup4RM0dmzNrFxqmMahW4DQ9OccFak6FqoPQKpfr7irusP/I1PL/7m/KSm/mwjBFMObB9y1LmLprr6Y3kQAyjIxNqbiwVssJyACbVSaODyErG+7UFave0VHsUnxM3oYnCjnh9/XpX5xqXacFlbmU9fsC0bM/Tz9Xc6d1PVc4oNKdmIbjY3B1jvuGh2UxKtj4z1FCysNvMt7GoU7+N4eJcQPpAwT8q2GSxxUTXLJl35vRn8u2L4gTNDYc9bxDYbtRFvRQlnWWX9B2OaGAJwcOu2HrQECgYEA4xZwxgA7vc5L5c+1HjzdIZsD1D1WvnidzZFmD/Qfc8fbleUqFxG8TqbkB9ene45wqCy0utbhoPMC9/d0GlXXeOD8BnJQgmhnwXUcj6QM2FKpS6ludJ8CiRiTWY1kPew4ThzcWjVtHKrv4ieaodU6RpXRryEM5/5bLTSMB2GTc/kCgYEAzHQDfR96eROFRobHuYjmSrfTFJ45f9u5+y7ITZp1gEDVgFu+jriQItO8uhfHJQa4X5nrv7krTlQPmW9BJ7BvGadid0E03DKqBvEDlprpLfPWr891Y+WpvLn/j+Xywgp6D66ub33jNnhuKTPV01i5IxNvPIYv4kW/N/zR/zF5KakCgYEAtMxfCSWSavHed5/BYcuve1wB1m7nq0o4yTwj+Duy9ul+KH+F3UwfkrdJAf1uuO6VPzAozEDc7tnL2UTIyVbi8LifrzpAYzNguCPXk31XRLu7UiQZbvxSdnh8iGYME0kJIxfTUHcM4jAuQO6rLIGpnh0WDsrPjb1zNjCJ9C55yXECgYEAsSP7OdeiN3EQUhDIzxmr3iTy/7QvQXZQ5y6bYZFoKN0Dnpjeu61xRJuLsviTFKOD72De/1giC1WNxnS8UPTu7Z03FPgsInTLGASOBVjmm2ffJKhsn0cHD3tfz39+G10UcK36eKLrz+/8EjrVEq6Wiat2/0uMBVJE4O9tyttEjTECgYEAghljC9wBMEpAlK4E3YbYS1QgVWMjsk9VkAnBbJgUMlr2nJ2FrXcLLczY9s+L2E1ag5WPL36T2YC2CqfRFvFTAo8TvmRGBxnpWLgx2Lj/QkS/9iZGbGqHoF4D4nVwxx1LetmUVIwoYMDBXevunAg1OCvO2Mn32qkqCxOU3ZD5iIc=
      AUTH_SAML_entityId: pw-api.local:8080
      AUTH_SAML_ssoUrl: http://ssp.local/saml2/idp/SSOService.php
      AUTH_SAML_sloUrl: http://ssp.local/saml2/idp/SingleLogoutService.php
      APP_ENV: dev # use real components for emailer, auth, and passwordStore
#      APP_ENV: test # use fake components for emailer, auth, and passwordStore
      ID_BROKER_baseUrl: http://broker
      ID_BROKER_accessToken: abc123abc123
      ID_BROKER_assertValidBrokerIp: "false"

  pw-cron:
    image: silintl/idp-pw-api:develop-3.0
    depends_on:
      - db-pw
    volumes:
      - ./pw-api/config.php:/data/common/config/local.php
    environment:
      MYSQL_HOST: db-pw
      MYSQL_DATABASE: pw-api
      MYSQL_USER: pw-api
      MYSQL_PASSWORD: pw-api
      IDP_NAME: development
      ALERTS_EMAIL_ENABLED: "false"
      LOGO_URL: http://www.sil.org
      MAILER_USEFILES: "true"
      MAILER_HOST: smtp.gmail.com
      MAILER_USERNAME: dummy
      MAILER_PASSWORD: dummy
      ADMIN_EMAIL: admin@domain.com
      FROM_EMAIL: admin@domain.com
      FROM_NAME: Your friendly Help Desk team
      FRONT_COOKIE_SECURE: "false"
      RECAPTCHA_REQUIRED: "false"
      RECAPTCHA_SITE_KEY:
      RECAPTCHA_SECRET_KEY:
      UI_URL: http://pw-ui.local:9000/#
      UI_CORS_ORIGIN: http://pw-ui.local:9000
      HELP_CENTER_URL: https://google.com/
      LOGENTRIES_KEY:
      SUPPORT_PHONE:
      SUPPORT_EMAIL:
      SUPPORT_URL:
      SUPPORT_FEEDBACK:
      ZXCVBN_API_BASEURL: http://zxcvbn:3000
      ACCESS_TOKEN_HASH_KEY: nice long random string here
      ALERTS_EMAIL: admin@domain.com
    command: whenavail db-pw 3306 100 /data/run-cron.sh

  phpmyadmin-pw:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8003:80"
    depends_on:
      - db-pw
    environment:
      PMA_HOST: db-pw
      PMA_USER: pw-api
      PMA_PASSWORD: pw-api

  zxcvbn:
    image: wcjr/zxcvbn-api:1.1.0
    ports:
        - "3000"

  pw-ui:
    image: silintl/idp-pw-ui:develop
    ports:
       - "9000:9000"
    volumes:
      - ./pw-ui/password.env.js:/data/app/password.env.js

  sync:
    image: silintl/idp-id-sync:develop
    ports:
      - "9090:80"
    depends_on:
      - broker
    environment:
      APP_ENV: dev
      ID_BROKER_CONFIG_accessToken: abc123abc123
      ID_BROKER_CONFIG_baseUrl: http://broker
      ID_BROKER_ADAPTER: idp
      ID_STORE_ADAPTER: googlesheets
      ID_STORE_CONFIG_applicationName: idp-in-a-box
      ID_STORE_CONFIG_jsonAuthFilePath: /data/google-auth.json
      ID_STORE_CONFIG_spreadsheetId: 123456
      ID_SYNC_ACCESS_TOKENS: abc123abc123
      IDP_NAME: development
      LOGENTRIES_KEY:
