name: Terraform

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    uses: silinternational/workflows/.github/workflows/terraform.yml@main
    with:
      terraform-version: '~> 1.1'
      test-dir: test
